
title: Apartment Ocean Guides
logo: "/assets/images/apartmentoceanlogo.png"
description: Apartment Ocean installation Guides
theme: just-the-docs
color_scheme: webchat

plugins:
  - "jekyll-github-metadata"

exclude: ['vendor']

# Footer content 
# appears at the bottom of every page's main content
footer_content: "&copy Apartment Ocean 2020 All Rights Reserved"
