# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'nokogiri'
gem "rack", ">= 2.1.4"
gem 'rspec'
# gem 'jekyll', '3.9.0'
gem 'github-pages', "~> 207", group: :jekyll_plugins
gem "just-the-docs"
gem "rake"
ruby "2.7.1"
# gem "rails"
