# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'nokogiri'
gem 'rack', '~> 2.0.1'
gem 'rspec'
# gem 'jekyll', '3.9.0'
gem 'github-pages', group: :jekyll_plugins

# gem "rails"
